#!/bin/bash
# GIVRwrld 128 GB single-node setup (Ubuntu 24.04)
# Run on the server from the repo root: bash ops/setup-128gb-node.sh
# Prereqs: repo is at /opt/givrwrld (clone or copy), you are root or sudo.

set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"
DOMAIN="${DOMAIN:-givrwrldservers.com}"
API_URL="https://api.${DOMAIN}"
PANEL_URL="https://panel.${DOMAIN}"
FRONTEND_URL="https://www.${DOMAIN}"

echo "[1/9] Updating system and installing base packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl git ufw

echo "[2/9] Installing Node.js 20..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y -qq nodejs

echo "[3/9] Installing PM2..."
npm install -g pm2

echo "[4/9] Installing MariaDB and Redis..."
apt-get install -y -qq mariadb-server redis-server
systemctl enable mariadb redis-server
systemctl start mariadb redis-server

echo "[5/9] Creating app_core DB and users (grants + schema + migrations)..."
mysql -u root < "$REPO_ROOT/sql/grants.sql"
mysql -u root app_core < "$REPO_ROOT/sql/app_core.sql"
for f in "$REPO_ROOT/sql/migrations"/*.sql; do
  [ -f "$f" ] && mysql -u root app_core < "$f" && echo "  Applied $(basename "$f")"
done

echo "[6/9] Seeding plans and region/node (us-east, node 1)..."
mysql -u root app_core < "$REPO_ROOT/sql/scripts/seed-12-games-plans.sql"
mysql -u root app_core -e "
  INSERT IGNORE INTO regions (code, display_name) VALUES ('us-east','US East'), ('us-central','US Central');
  INSERT INTO ptero_nodes (ptero_node_id, name, region_code, max_ram_gb, max_disk_gb, reserved_headroom, enabled)
  VALUES (1, 'Rise-3-128', 'us-east', 128, 1000, 20, 1)
  ON DUPLICATE KEY UPDATE name=VALUES(name), region_code=VALUES(region_code), max_ram_gb=VALUES(max_ram_gb), max_disk_gb=VALUES(max_disk_gb);
  INSERT INTO region_node_map (region_code, ptero_node_id, weight) VALUES ('us-east', 1, 100) ON DUPLICATE KEY UPDATE weight=100;
"

echo "[7/9] Installing Docker and Pterodactyl deps..."
apt-get install -y -qq ca-certificates curl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
apt-get update -qq
apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
systemctl enable docker
systemctl start docker

echo "[8/9] Installing nginx and certbot..."
apt-get install -y -qq nginx certbot python3-certbot-nginx

echo "[9/9] Firewall (22, 80, 443, 8082, 2022)..."
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 8082/tcp
ufw allow 2022/tcp
ufw --force enable || true

echo "--- App install (npm, env, build) ---"
cd "$REPO_ROOT"
npm install
cd api && npm install && cd ..

# Minimal api/.env for DB and build (you must add PayPal, Panel key, JWT, SMTP later)
if [ ! -f api/.env ]; then
  cat > api/.env << EOF
# Generated by setup-128gb-node.sh — add PayPal, PANEL_APP_KEY, JWT_SECRET, SMTP, etc.
NODE_ENV=production
PORT=3001
MYSQL_HOST=127.0.0.1
MYSQL_PORT=3306
MYSQL_USER=app_rw
MYSQL_PASSWORD=Y3bD4KZDnxoeh43voH9ZCRESg0LjSugD
MYSQL_DATABASE=app_core
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
PANEL_URL=$PANEL_URL
FRONTEND_URL=$FRONTEND_URL
PUBLIC_SITE_URL=$FRONTEND_URL
PAYPAL_SANDBOX=true
# Set PTERO_DEFAULT_ALLOCATION_ID after creating allocations in Panel
# Add: PAYPAL_CLIENT_ID, PAYPAL_CLIENT_SECRET, PAYPAL_WEBHOOK_ID, PANEL_APP_KEY, JWT_SECRET, JWT_REFRESH_SECRET, SMTP_*
EOF
  echo "Created api/.env (minimal). Edit and add PayPal, Panel key, JWT, SMTP before go-live."
fi

# Frontend build (API URL for production)
export VITE_API_URL="$API_URL"
npm run build

# Pterodactyl: avoid binding host 3306 (host MariaDB is on 3306)
PTERO_COMPOSE="$REPO_ROOT/pterodactyl/docker-compose.yml"
if [ -f "$PTERO_COMPOSE" ] && grep -q '3306:3306' "$PTERO_COMPOSE"; then
  sed -i 's/- "3306:3306"/# - "3306:3306"  # host uses 3306 for app_core/' "$PTERO_COMPOSE"
fi

echo ""
echo "=== Setup script done. Next steps (manual) ==="
echo "1. Edit api/.env: add PAYPAL_CLIENT_ID, PAYPAL_CLIENT_SECRET, PAYPAL_WEBHOOK_ID, PANEL_APP_KEY, JWT_SECRET, JWT_REFRESH_SECRET, SMTP vars, PTERO_DEFAULT_ALLOCATION_ID."
echo "2. Pterodactyl: cd $REPO_ROOT/pterodactyl && echo 'MYSQL_ROOT_PASSWORD=choose_a_password' > .env && echo 'DB_PASSWORD=choose_panel_db_password' >> .env && docker compose up -d"
echo "3. In Panel (https://panel.$DOMAIN after nginx+TLS): create admin user, Application API key, allocations; set node memory limit ~105000 MB."
echo "4. Sync catalog: cd $REPO_ROOT && node api/scripts/sync-pterodactyl-catalog.js --apply"
echo "5. region_node_map: mysql -u root app_core -e \"INSERT INTO region_node_map (region_code, ptero_node_id, weight) VALUES ('us-east', 1, 100) ON DUPLICATE KEY UPDATE weight=100;\""
echo "6. nginx: copy ops/nginx/*.conf.example to /etc/nginx/sites-available, replace <your-domain> with $DOMAIN, enable sites, certbot --nginx -d www.$DOMAIN -d api.$DOMAIN -d panel.$DOMAIN"
echo "7. PM2: cd $REPO_ROOT && pm2 start ecosystem.config.cjs && pm2 save && pm2 startup"
echo ""
